# Generated by Django 4.1 on 2023-01-03 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base_Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_name", models.CharField(max_length=100)),
                ("trip_icon", models.CharField(max_length=100)),
                ("trip_icon_color", models.CharField(max_length=100)),
                (
                    "trip_img",
                    models.CharField(
                        default="Some Location to Access Deafult Image", max_length=200
                    ),
                ),
                ("num_people", models.IntegerField(null=True)),
                ("public", models.BooleanField(default=False)),
                ("_trip_uuid", models.UUIDField(default=uuid.uuid4)),
                (
                    "alert_time",
                    models.DurationField(default=datetime.timedelta(days=1)),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "authorized_users",
                    models.ManyToManyField(
                        related_name="authorized_users", to="users.user_extension"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Planned_trip",
            fields=[
                (
                    "base_trip_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trips.base_trip",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "_default_time_delta",
                    models.DurationField(default=datetime.timedelta(days=7)),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("trips.base_trip", models.Model),
        ),
        migrations.CreateModel(
            name="Unplanned_trip",
            fields=[
                (
                    "base_trip_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="trips.base_trip",
                    ),
                ),
                ("start_time", models.DateTimeField(null=True)),
                ("end_time", models.DateTimeField(null=True)),
                (
                    "_default_time_delta",
                    models.DurationField(default=datetime.timedelta(days=7)),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("trips.base_trip", models.Model),
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("destination_name", models.CharField(max_length=100)),
                (
                    "_destination_uuid",
                    models.UUIDField(default=uuid.uuid4, unique=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user_added",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user_extension",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="base_trip",
            name="destinations",
            field=models.ManyToManyField(
                related_name="destinations", to="trips.destination"
            ),
        ),
        migrations.AddField(
            model_name="base_trip",
            name="pending_permission",
            field=models.ManyToManyField(
                related_name="pending_permission", to="users.user_extension"
            ),
        ),
        migrations.AddField(
            model_name="base_trip",
            name="trip_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user_extension"
            ),
        ),
        migrations.AddField(
            model_name="base_trip",
            name="users_that_liked_trip",
            field=models.ManyToManyField(
                related_name="Trips_User_liked", to="users.user_extension"
            ),
        ),
        migrations.AddField(
            model_name="base_trip",
            name="users_that_questioned_trip",
            field=models.ManyToManyField(
                related_name="Trips_User_questioned", to="users.user_extension"
            ),
        ),
        migrations.AddField(
            model_name="base_trip",
            name="users_that_starred_trip",
            field=models.ManyToManyField(
                related_name="Trips_User_starred", to="users.user_extension"
            ),
        ),
    ]
