# Generated by Django 4.1 on 2023-01-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_base_trip_trip_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="destination_latitude",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="destination",
            name="destination_longitude",
            field=models.CharField(default="", max_length=100),
        ),
    ]
