# Generated by Django 4.1 on 2023-01-03 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("events", "0001_initial"),
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base_notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("main_icon", models.CharField(default="default", max_length=150)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("_notification_uuid", models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name="Trip_Time_Alert",
            fields=[
                (
                    "base_notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.base_notification",
                    ),
                ),
                (
                    "recieving_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_alert",
                        to="users.user_extension",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trips.base_trip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("notifications.base_notification", models.Model),
        ),
        migrations.CreateModel(
            name="Trip_request",
            fields=[
                (
                    "base_notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.base_notification",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_time",
                    models.DurationField(
                        default=datetime.timedelta(days=-1, seconds=86100)
                    ),
                ),
                (
                    "recieving_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recieving_user_trip_request",
                        to="users.user_extension",
                    ),
                ),
                (
                    "sending_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending_user_trip_request",
                        to="users.user_extension",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_requests",
                        to="trips.base_trip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("notifications.base_notification", models.Model),
        ),
        migrations.CreateModel(
            name="General_Trip_Notification",
            fields=[
                (
                    "base_notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.base_notification",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_time",
                    models.DurationField(
                        default=datetime.timedelta(days=-1, seconds=86100)
                    ),
                ),
                ("notification_type", models.IntegerField()),
                (
                    "recieving_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recieving_user_general_trip_request",
                        to="users.user_extension",
                    ),
                ),
                (
                    "sending_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending_user_general_trip_request",
                        to="users.user_extension",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_trip_notification",
                        to="trips.base_trip",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("notifications.base_notification", models.Model),
        ),
        migrations.CreateModel(
            name="Friend_request",
            fields=[
                (
                    "base_notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.base_notification",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_time",
                    models.DurationField(
                        default=datetime.timedelta(days=-1, seconds=86100)
                    ),
                ),
                (
                    "recieving_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recieving_user_friend_request",
                        to="users.user_extension",
                    ),
                ),
                (
                    "sending_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sending_user_friend_request",
                        to="users.user_extension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("notifications.base_notification", models.Model),
        ),
        migrations.CreateModel(
            name="Event_alert",
            fields=[
                (
                    "base_notification_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="notifications.base_notification",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.base_event",
                    ),
                ),
                (
                    "recieving_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trip_alerts",
                        to="users.user_extension",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("notifications.base_notification", models.Model),
        ),
    ]
